"""Backend contracts. All time arguments use monotonic seconds; mock units are SI."""
from abc import ABC, abstractmethod
from .models import DeviceStatus

class DeviceAdapter(ABC):
    @abstractmethod
    def connect(self) -> None: ...
    @abstractmethod
    def disconnect(self) -> None: ...
    @abstractmethod
    def get_status(self) -> DeviceStatus: ...
    def update(self, dt: float) -> None:
        """Poll a real backend, advance a simulated backend. Must not block."""

class MotorAdapter(DeviceAdapter):
    def set_torque(self, torque: float) -> None:
        raise NotImplementedError('This motor does not support torque control')
    @abstractmethod
    def enable(self) -> None: ...
    @abstractmethod
    def disable(self) -> None: ...
    @abstractmethod
    def jog(self, velocity: float) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...
    @abstractmethod
    def get_position(self) -> float: ...
    @abstractmethod
    def get_velocity(self) -> float: ...
    @abstractmethod
    def get_error(self) -> str: ...

class CameraAdapter(DeviceAdapter):
    @abstractmethod
    def is_connected(self) -> bool: ...
    @abstractmethod
    def get_frame(self): ...
    @abstractmethod
    def get_fps(self) -> float: ...
    @abstractmethod
    def get_frame_count(self) -> int: ...
    @abstractmethod
    def get_drop_count(self) -> int: ...

class FaultInjectable(ABC):
    @abstractmethod
    def inject_fault(self, fault: str, active: bool) -> None: ...
